version: '3.9'

services:
  backend:
    build:
      context: ./src/infra
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app/app
      - ./src/infra:/app/infra

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  pgdata:
